name: G-IF
version: '${project.version}'
main: me.filipe.gitemframe.GItemFrame
api-version: 1.19
authors: [ GamerExxtreme ]
description: Simple Item Frame plugin.

commands:
  toggleif:
    usage: /<command>
